name: Test
on:
  pull_request:

jobs:
  check-rebased:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check if rebased on master
        run: |
          git fetch origin master
          PR_HEAD=$(git rev-parse HEAD)
          MASTER_HEAD=$(git rev-parse origin/master)
          if git merge-base --is-ancestor $MASTER_HEAD $PR_HEAD; then
            echo "PR is rebased on master"
          else
            echo "PR is not rebased on master"
            exit 1
          fi

  check-content:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: package.json
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
            node_modules/.package-lock.json

      - name: Build project
        run: |
          npm install
          npm run build
          npm run format
          npm run format-check
          npm prune --omit=dev

      - name: Check git status
        run: |
          git status
          if [ -n "$(git status --porcelain)" ]; then
             echo "Changes detected, please ensure all dependencies updates are checked in."
          fi

  call-tests:
    uses: ./.github/workflows/test.yml
    permissions:
      contents: read
      pull-requests: read
    secrets: inherit